- name: Remove and copy a new file with same name
  hosts: all
  become: yes
  tasks:
   - name: Remove a file
     ansible.builtin.file:
      path: /var/log/saipavan/Messagefile
      state: absent
   - name: Message file copying
     ansible.builtin.copy:
      src: Messagefile
      dest: /var/log/saipavan/