- name: To Replace text in file
  hosts: all
  become: yes
  tasks:
   - name: Search File and replace it with new one
     ansible.builtin.replace:
      path : /var/log/saipavan/Messagefile
      regexp: Third
      replace: Fourth
      backup: yes