---
- name: HTTPS AND GIT INSTALL
  hosts: all
  become: true
  tasks:
   - name: Https Install
     ansible.builtin.dnf:
      name:
        - httpd
        - git
      state: present
   - name: Service start and enable
     ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
