- name: Package installation
  hosts: all
  become: true
  vars:
   packages:
    - httpd
    - git
    - vim
  tasks:
   - name: Install the packages using loops
     ansible.builtin.dnf:
      name: {{ "item" }}
      state: present
     loop: {{ "packages" }}
   - name: Start and enable service
     ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: true