---
- name: Install nginx
  hosts: all
  become: true
  tasks:
   - name: Install nginx
     ansible.builtin.dnf:
      name: nginx
      state: present
   - name: Install Tomcat
     ansible.builtin.service:
      name: Tomcat
      state: started
      enabled: yes
...
