---
- name: Install nginx
  hosts: all
  become: true
  tasks:
   - name: Install nginx
     ansible.builtin.dnf:
      name: nginx
      state: present
   - name: Nginx enable and start
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
...
