- name: Patch OperatingSystem
  hosts: all
  become: true
  tasks:
   - name: Patch the server
     ansible.builtin.dnf:
      name: "*"
      state: latest
      security: true
      exclude:
        - kernel